[package]
name = "anole"
version = "0.0.25"
edition = "2024"
description = "The Anole programming language"
license = "MIT"
repository = "https://github.com/anole-lang/anole"

[lints.rust]
unsafe_code = "forbid"

[lib]
name = "anole"
path = "src/lib.rs"

[[bin]]
name = "anole"
path = "src/main.rs"

[[test]]
name = "compile_tests"
path = "tests/compile_tests.rs"
harness = false

[profile.release]
lto = true
strip = true
