#pragma once

#include "object.hpp"
#include "boolobject.hpp"
#include "contobject.hpp"
#include "dictobject.hpp"
#include "enumobject.hpp"
#include "funcobject.hpp"
#include "listobject.hpp"
#include "noneobject.hpp"
#include "thunkobject.hpp"
#include "floatobject.hpp"
#include "moduleobject.hpp"
#include "stringobject.hpp"
#include "integerobject.hpp"
#include "builtinfuncobject.hpp"
